# Create a Docker Image from SourceCode
version: '3.8'
services:
  svideo-db: 
    image: postgres:15.0
    container_name: svideo-db
    ports:
      - 5436:5432 # { port in host (this PC) } : {port in (Container) Docker }
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sv123456098
      POSTGRES_DB: sharevideodb
    networks:
      - mnestjs_network 
networks: # Multiple services on a network "mnestjs_network"
  mnestjs_network: 